apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ include "elydora.namespace" . }}
  labels:
    {{- include "elydora.labels" . | nindent 4 }}
    app: api
spec:
  ports:
    - port: 8787
      targetPort: 8787
  selector:
    app: api
