apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: {{ include "elydora.namespace" . }}
  labels:
    {{- include "elydora.labels" . | nindent 4 }}
    app: api
spec:
  replicas: {{ .Values.replicaCount.api }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.api.repository }}:{{ .Values.image.api.tag }}"
          imagePullPolicy: {{ .Values.image.api.pullPolicy }}
          ports:
            - containerPort: 8787
          envFrom:
            - configMapRef:
                name: elydora-config
            - secretRef:
                name: elydora-secret
          resources:
            {{- toYaml .Values.resources.api | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8787
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8787
            initialDelaySeconds: 20
            periodSeconds: 20
