apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  namespace: {{ include "elydora.namespace" . }}
  labels:
    {{- include "elydora.labels" . | nindent 4 }}
    app: console
spec:
  replicas: {{ .Values.replicaCount.console }}
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
        - name: console
          image: "{{ .Values.image.console.repository }}:{{ .Values.image.console.tag }}"
          imagePullPolicy: {{ .Values.image.console.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: elydora-config
                  key: NEXT_PUBLIC_API_BASE_URL
          resources:
            {{- toYaml .Values.resources.console | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 20
