apiVersion: v1
kind: Service
metadata:
  name: console
  namespace: {{ include "elydora.namespace" . }}
  labels:
    {{- include "elydora.labels" . | nindent 4 }}
    app: console
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: console
