apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: {{ include "elydora.namespace" . }}
  labels:
    {{- include "elydora.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: db-migrate
          image: "{{ .Values.image.api.repository }}:{{ .Values.image.api.tag }}"
          imagePullPolicy: {{ .Values.image.api.pullPolicy }}
          command: ["node", "dist/migrate.js"]
          envFrom:
            - configMapRef:
                name: elydora-config
            - secretRef:
                name: elydora-secret
