apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: {{ include "elydora.namespace" . }}
  labels:
    {{- include "elydora.labels" . | nindent 4 }}
    app: minio
spec:
  ports:
    - port: 9000
      targetPort: 9000
      name: api
    - port: 9001
      targetPort: 9001
      name: console
  selector:
    app: minio
