apiVersion: v1
kind: Secret
metadata:
  name: elydora-secret
  namespace: {{ include "elydora.namespace" . }}
  labels:
    {{- include "elydora.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "elydora.databaseUrl" . | quote }}
  JWT_SECRET: {{ .Values.api.jwtSecret | quote }}
  ELYDORA_SIGNING_KEY: {{ .Values.api.signingKey | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  MINIO_SECRET_KEY: {{ .Values.minio.rootPassword | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.rootPassword | quote }}
