import { PROTECTED_RUNTIME_READER } from './runtime-reader-template.js';

export { generateGuardScript } from './guard-template.js';
export type { GuardScriptOptions } from './guard-template.js';

export interface HookScriptOptions {
  readonly failClosed?: boolean;
  readonly nativePayload?: boolean;
  readonly successOutput?: string;
}

/** Generates a self-contained Node.js audit hook with no SDK runtime dependency. */
export function generateHookScript(
  agentName: string,
  agentId: string,
  options: HookScriptOptions = {},
): string {
  const failClosed = options.failClosed ?? false;
  const nativePayload = options.nativePayload ?? false;
  const successOutput = options.successOutput ?? '';
  return `#!/usr/bin/env node
'use strict';

// Elydora audit hook for ${agentName}. Generated by @elydora/sdk.
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');

const AGENT_NAME = ${JSON.stringify(agentName)};
const AGENT_ID = ${JSON.stringify(agentId)};
const SUCCESS_OUTPUT = ${JSON.stringify(successOutput)};
const FAIL_CLOSED = ${JSON.stringify(failClosed)};
const NATIVE_PAYLOAD = ${JSON.stringify(nativePayload)};
const ELYDORA_DIR = path.join(os.homedir(), '.elydora');
const CONFIG_PATH = path.join(ELYDORA_DIR, AGENT_ID, 'config.json');
const KEY_PATH = path.join(ELYDORA_DIR, AGENT_ID, 'private.key');
const CHAIN_STATE_PATH = path.join(ELYDORA_DIR, AGENT_ID, 'chain-state.json');
const ERROR_LOG_PATH = path.join(ELYDORA_DIR, AGENT_ID, 'error.log');
const ZERO_CHAIN_HASH = 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA';

${PROTECTED_RUNTIME_READER}

function base64urlEncode(data) {
  const buffer = Buffer.isBuffer(data) ? data : Buffer.from(data);
  return buffer.toString('base64url');
}

function jcsCanonicalise(value) {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'boolean' || typeof value === 'number') return JSON.stringify(value);
  if (typeof value === 'string') return JSON.stringify(value);
  if (Array.isArray(value)) return '[' + value.map(jcsCanonicalise).join(',') + ']';
  if (typeof value === 'object') {
    const pairs = [];
    for (const key of Object.keys(value).sort()) {
      if (value[key] !== undefined) {
        pairs.push(JSON.stringify(key) + ':' + jcsCanonicalise(value[key]));
      }
    }
    return '{' + pairs.join(',') + '}';
  }
  return JSON.stringify(value);
}

function sha256Base64url(data) {
  const input = typeof data === 'string' ? Buffer.from(data, 'utf-8') : data;
  return base64urlEncode(crypto.createHash('sha256').update(input).digest());
}

function computePayloadHash(payload) {
  return sha256Base64url(jcsCanonicalise(payload));
}

function computeChainHash(previous, payload, operationId, issuedAt) {
  return sha256Base64url(previous + '|' + payload + '|' + operationId + '|' + issuedAt);
}

const PKCS8_ED25519_PREFIX = Buffer.from([
  0x30, 0x2e, 0x02, 0x01, 0x00, 0x30, 0x05,
  0x06, 0x03, 0x2b, 0x65, 0x70, 0x04, 0x22, 0x04, 0x20,
]);

function parsePrivateKey(raw) {
  let value = raw.toString('utf-8');
  if (value.endsWith('\\r\\n')) value = value.slice(0, -2);
  else if (value.endsWith('\\n')) value = value.slice(0, -1);
  if (!value || value.includes('\\r') || value.includes('\\n') || value.includes('\\0')) {
    throw new Error('Private key file must contain exactly one line');
  }
  const seed = Buffer.from(value, 'base64url');
  if (seed.length !== 32 || base64urlEncode(seed) !== value) {
    throw new Error('Private key must be a canonical 32-byte base64url value');
  }
  return seed;
}

function signEd25519(seed, data) {
  const pkcs8 = Buffer.concat([PKCS8_ED25519_PREFIX, seed]);
  const key = crypto.createPrivateKey({ key: pkcs8, format: 'der', type: 'pkcs8' });
  return base64urlEncode(crypto.sign(null, data, key));
}

function uuidv7() {
  const now = Date.now();
  const random = crypto.randomBytes(10);
  const bytes = Buffer.alloc(16);
  bytes[0] = (now / 2 ** 40) & 0xff;
  bytes[1] = (now / 2 ** 32) & 0xff;
  bytes[2] = (now / 2 ** 24) & 0xff;
  bytes[3] = (now / 2 ** 16) & 0xff;
  bytes[4] = (now / 2 ** 8) & 0xff;
  bytes[5] = now & 0xff;
  bytes[6] = 0x70 | (random[0] & 0x0f);
  bytes[7] = random[1];
  bytes[8] = 0x80 | (random[2] & 0x3f);
  bytes[9] = random[3];
  bytes[10] = random[4];
  bytes[11] = random[5];
  bytes[12] = random[6];
  bytes[13] = random[7];
  bytes[14] = random[8];
  bytes[15] = random[9];
  const hex = bytes.toString('hex');
  return hex.slice(0, 8) + '-' + hex.slice(8, 12) + '-' + hex.slice(12, 16) + '-' +
    hex.slice(16, 20) + '-' + hex.slice(20);
}

function logError(error) {
  try {
    const message = new Date().toISOString() + ' [' + AGENT_NAME + '] ' +
      (error.stack || error.message || String(error)) + '\\n';
    appendProtectedText(ERROR_LOG_PATH, 'Error log', message);
  } catch (logFailure) {
    process.stderr.write('[Elydora audit] Failed to write error log: ' + logFailure.message + '\\n');
  }
}

function readChainState() {
  let raw;
  try {
    raw = readProtectedFile(
      CHAIN_STATE_PATH,
      'Chain state',
      MAX_PROTECTED_CONFIG_BYTES,
    ).toString('utf-8');
  } catch (error) {
    if (hasRuntimeErrorCode(error, 'ENOENT')) return ZERO_CHAIN_HASH;
    throw new Error('Failed to read chain state: ' + error.message);
  }
  let state;
  try {
    state = JSON.parse(raw);
  } catch (error) {
    throw new Error('Chain state is invalid JSON: ' + error.message);
  }
  if (!state || typeof state.prev_chain_hash !== 'string' ||
      !/^[A-Za-z0-9_-]{43}$/.test(state.prev_chain_hash)) {
    throw new Error('Chain state contains an invalid prev_chain_hash');
  }
  return state.prev_chain_hash;
}

function writeChainState(chainHash) {
  writeProtectedJson(CHAIN_STATE_PATH, 'Chain state', { prev_chain_hash: chainHash });
}

function readConfigAndKey() {
  const raw = readProtectedFile(
    CONFIG_PATH,
    'Agent config',
    MAX_PROTECTED_CONFIG_BYTES,
  ).toString('utf-8');
  let config;
  try {
    config = JSON.parse(raw);
  } catch (error) {
    throw new Error('Agent config is invalid JSON: ' + error.message);
  }
  if (!config || typeof config !== 'object') throw new Error('Agent config must be an object');
  if (config.agent_name !== AGENT_NAME || config.agent_id !== AGENT_ID) {
    throw new Error('Agent config identity does not match the generated audit hook');
  }
  for (const field of ['org_id', 'agent_id', 'kid']) {
    if (typeof config[field] !== 'string' || !config[field]) {
      throw new Error('Agent config is missing ' + field);
    }
  }
  if (config.token !== undefined && typeof config.token !== 'string') {
    throw new Error('Agent config token must be a string');
  }
  const baseUrl = config.base_url || 'https://api.elydora.com';
  if (typeof baseUrl !== 'string') throw new Error('Agent config base_url must be a string');
  const parsedBaseUrl = new URL(baseUrl);
  if (!['http:', 'https:'].includes(parsedBaseUrl.protocol)) {
    throw new Error('Agent config base_url must use HTTP or HTTPS');
  }
  return {
    config,
    baseUrl: baseUrl.replace(/\\\/+$/, ''),
    privateKey: parsePrivateKey(readProtectedFile(KEY_PATH, 'Private key')),
  };
}

async function readHookInput() {
  const chunks = [];
  for await (const chunk of process.stdin) chunks.push(chunk);
  const raw = Buffer.concat(chunks).toString('utf-8').trim();
  if (!raw) throw new Error('Hook input is empty');
  let value;
  try {
    value = JSON.parse(raw);
  } catch (error) {
    throw new Error('Hook input is invalid JSON: ' + error.message);
  }
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error('Hook input must contain a JSON object');
  }
  return value;
}

async function submitOperation(hookData, runtime) {
  const toolEvent = hookData.tool_result && typeof hookData.tool_result === 'object'
    ? hookData.tool_result
    : hookData.tool_call && typeof hookData.tool_call === 'object'
      ? hookData.tool_call
      : {};
  const toolName = hookData.tool_name || hookData.toolName || hookData.name ||
    toolEvent.name || 'unknown';
  const toolInput = hookData.tool_input || hookData.toolInput || hookData.input ||
    hookData.parameters || toolEvent.input || {};
  const sessionId = hookData.conversation_id || hookData.session_id || hookData.sessionId ||
    hookData.session || hookData.taskId || 'unknown';
  const previousHash = readChainState();
  const operationId = uuidv7();
  const issuedAt = Date.now();
  const payload = NATIVE_PAYLOAD ? hookData : {
    tool_name: toolName,
    tool_input: toolInput,
    session_id: sessionId,
  };
  const payloadHash = computePayloadHash(payload);
  const chainHash = computeChainHash(previousHash, payloadHash, operationId, issuedAt);
  const unsigned = {
    op_version: '1.0',
    operation_id: operationId,
    org_id: runtime.config.org_id,
    agent_id: runtime.config.agent_id,
    issued_at: issuedAt,
    ttl_ms: 30000,
    nonce: base64urlEncode(crypto.randomBytes(16)),
    operation_type: 'ai.tool_use',
    subject: { session_id: sessionId },
    action: { tool: toolName },
    payload,
    payload_hash: payloadHash,
    prev_chain_hash: previousHash,
    agent_pubkey_kid: runtime.config.kid,
  };
  const signature = signEd25519(
    runtime.privateKey,
    Buffer.from(jcsCanonicalise(unsigned), 'utf-8'),
  );
  const operation = { ...unsigned, chain_hash: chainHash, signature };
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 5000);
  try {
    const headers = { 'Content-Type': 'application/json', Accept: 'application/json' };
    if (runtime.config.token) headers.Authorization = 'Bearer ' + runtime.config.token;
    const response = await fetch(runtime.baseUrl + '/v1/operations', {
      method: 'POST',
      headers,
      body: JSON.stringify(operation),
      signal: controller.signal,
    });
    if (response.ok) {
      writeChainState(chainHash);
      return;
    }
    const responseBody = await response.text();
    if (response.status === 400 && responseBody) {
      let failure;
      try { failure = JSON.parse(responseBody); } catch (error) {
        throw new Error('Audit API returned invalid error JSON: ' + error.message);
      }
      if (failure.error && failure.error.code === 'PREV_HASH_MISMATCH') {
        const match = String(failure.error.message || '').match(
          /Expected prev_chain_hash "([A-Za-z0-9_-]{43})"/,
        );
        if (match) {
          writeChainState(match[1]);
          logError(new Error('Chain hash resynced to server: ' + match[1]));
        }
      }
    }
    throw new Error('Audit API returned HTTP ' + response.status);
  } finally {
    clearTimeout(timeout);
  }
}

async function main() {
  try {
    const hookData = await readHookInput();
    const runtime = readConfigAndKey();
    await submitOperation(hookData, runtime);
  } catch (error) {
    logError(error);
    if (FAIL_CLOSED) throw error;
  }
}

main().then(() => {
  if (SUCCESS_OUTPUT) process.stdout.write(SUCCESS_OUTPUT);
}).catch((error) => {
  process.stderr.write('[Elydora audit] ' + (error.stack || error.message || String(error)) + '\\n');
  process.exitCode = 1;
});
`;
}
