export { ElydoraClient } from './client.js';
export { ElydoraError } from './errors.js';
export { INTEGRATION_TYPES } from './types.js';

export {
  jcsCanonicalise,
  sha256Base64url,
  computeChainHash,
  computePayloadHash,
  signEd25519,
  derivePublicKey,
  ZERO_CHAIN_HASH,
} from './crypto.js';

export {
  uuidv7,
  generateNonce,
  base64urlEncode,
  base64urlDecode,
} from './utils.js';

export type {
  AgentStatus,
  KeyStatus,
  ExportStatus,
  RbacRole,
  IntegrationType,
  AdminAction,
  ErrorCode,

  Agent,
  AgentKey,
  Operation,
  Receipt,
  Epoch,
  Organization,
  AdminEvent,
  AgentAssignment,
  User,
  Export,

  EOR,
  EAR,

  ElydoraClientConfig,
  CreateOperationParams,
  RegisterAgentRequest,
  RegisterAgentResponse,
  GetAgentResponse,
  ListAgentsResponse,
  UpdateAgentRequest,
  UpdateAgentResponse,
  FreezeAgentResponse,
  UnfreezeAgentResponse,
  DeleteAgentResponse,
  SubmitOperationResponse,
  GetOperationResponse,
  VerifyOperationResponse,
  AuditQueryRequest,
  AuditQueryResponse,
  GetEpochResponse,
  ListEpochsResponse,
  CreateExportRequest,
  CreateExportResponse,
  GetExportResponse,
  ListExportsResponse,
  GetMeResponse,
  IssueApiTokenResponse,
  RotateApiTokenResponse,
  JWK,
  JWKSResponse,
  HealthResponse,
  DeepHealthResponse,
  Webhook,
  ListWebhooksResponse,
  RegisterWebhookResponse,
  ListMembersResponse,
  ListAdminEventsResponse,
  AuthRegisterResponse,
  AuthLoginResponse,
  ErrorResponse,
} from './types.js';
